export const GET_BUILDINGS_FETCHING = 'GET_BUILDINGS_FETCHING';
export const GET_BUILDINGS_FULFILLED = 'GET_BUILDINGS_FULFILLED';
export const GET_BUILDINGS_REJECTED = 'GET_BUILDINGS_REJECTED';

export const ADD_BUILDING_FETCHING = 'ADD_BUILDING_FETCHING';
export const ADD_BUILDING_FULFILLED = 'ADD_BUILDING_FULFILLED';
export const ADD_BUILDING_REJECTED = 'ADD_BUILDING_REJECTED';

export const UPDATE_BUILDING_FETCHING = 'UPDATE_BUILDING_FETCHING';
export const UPDATE_BUILDING_FULFILLED = 'UPDATE_BUILDING_FULFILLED';
export const UPDATE_BUILDING_REJECTED = 'UPDATE_BUILDING_REJECTED';

export const DELETE_BUILDING_FETCHING = 'DELETE_BUILDING_FETCHING';
export const DELETE_BUILDING_FULFILLED = 'DELETE_BUILDING_FULFILLED';
export const DELETE_BUILDING_REJECTED = 'DELETE_BUILDING_REJECTED';
