export const GET_CONSTRUCTIONS = 'GET_CONSTRUCTIONS';
export const ADD_CONSTRUCTION = 'ADD_CONSTRUCTION';
export const UPDATE_CONSTRUCTION = 'UPDATE_CONSTRUCTION';
export const DELETE_CONSTRUCTION = 'DELETE_CONSTRUCTION';
