export const GET_CONSTRUCTIONS_FETCHING = 'GET_CONSTRUCTIONS_FETCHING';
export const GET_CONSTRUCTIONS_FULFILLED = 'GET_CONSTRUCTIONS_FULFILLED';
export const GET_CONSTRUCTIONS_REJECTED = 'GET_CONSTRUCTIONS_REJECTED';

export const ADD_CONSTRUCTION_FETCHING = 'ADD_CONSTRUCTION_FETCHING';
export const ADD_CONSTRUCTION_FULFILLED = 'ADD_CONSTRUCTION_FULFILLED';
export const ADD_CONSTRUCTION_REJECTED = 'ADD_CONSTRUCTION_REJECTED';

export const UPDATE_CONSTRUCTION_FETCHING = 'UPDATE_CONSTRUCTION_FETCHING';
export const UPDATE_CONSTRUCTION_FULFILLED = 'UPDATE_CONSTRUCTION_FULFILLED';
export const UPDATE_CONSTRUCTION_REJECTED = 'UPDATE_CONSTRUCTION_REJECTED';

export const DELETE_CONSTRUCTION_FETCHING = 'DELETE_CONSTRUCTION_FETCHING';
export const DELETE_CONSTRUCTION_FULFILLED = 'DELETE_CONSTRUCTION_FULFILLED';
export const DELETE_CONSTRUCTION_REJECTED = 'DELETE_CONSTRUCTION_REJECTED';
